server:
  port: 8080
  servlet:
    context-path: /api

client:
  url: "http://localhost:3000"

spring:
  application:
    name: React-To-Spring-Forums
  datasource:
    url: ${IDENTITY_SERVICE_DB_URL:jdbc:mysql://localhost:3306/identity_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${REACT_TO_SPRING_FORUMS_DB_URL:mongodb+srv://root:root@reacttospring.rhg23.mongodb.net/react-to-spring-forums-db?retryWrites=true&w=majority}
  jpa:
    show-sql: true
    open-in-view: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  accessSignerKey: ${ACCESS_SIGNER_KEY:N2d5cmwxaGZrbjQ2MTBvYXNodWNlYTUwYTlxemFvNnA0M2NkMzB4M281dXF1Y21zdGxiZTQ0eXVhamxvczYzd284OTFsb3ZlZWxsYmRxa2lkZ2I4OGZqOHR4d2RzamF4eXN3ZmJrc3FvbnFydHdvOXdxMXBjYzE0dGJweDNnbDM=}
  refreshSignerKey: ${REFRESH_SIGNER_KEY:a2M5OXR2Z3JuMmc3bnF6cTIwZ2JhZjBoZjlscWJiNTltc2E4ejVyeTFhZ2VvYjd2am43cHB5NHVobndtMHFoYnZ1NHg2eXAxY2dsenV3ZHFqd29vNzRobm4xMGNhMzJyMjJnNXFzZ3llbGh3a3Q5NWs1andxbWlyMzhmbTY0OXc=}
  valid-duration: ${VALID_DURATION:3600} # in second
  refreshable-duration: ${REFRESHABLE_DURATION:360000} # in second

app:
  init-admin-account:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
  role:
    admin:
      name: ADMIN
      description: "Admin has all authorization"
  controller:
    user:
      response:
        delete:
          success: "User has been deleted"
    role:
      response:
        delete:
          success: "Role has been deleted"
    permission:
        response:
          delete:
            success: "Permission has been deleted"
    authentication:
      response:
        logout:
            success: "Logout successfully"
        change-password:
          success: "Password has been changed"

open:
  api:
    title: "React To Spring Forums API"
    version: "v1.0.0"
    description: "API for React To Spring Forums"
    server:
      url: "http://localhost:8080/api"
      description: "Local Server."
    group:
      package-to-scan: "com.react_to_spring.React_To_Spring_Forums.controller"