server:
  port: 8080
  servlet:
    context-path: /api

client:
  url: "http://localhost:3000"

spring:
  application:
    name: React-To-Spring-Forums
  datasource:
    url: ${IDENTITY_SERVICE_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${REACT_TO_SPRING_FORUMS_DB_URL}
  jpa:
    show-sql: true
    open-in-view: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  accessSignerKey: ${ACCESS_SIGNER_KEY}
  refreshSignerKey: ${REFRESH_SIGNER_KEY}
  valid-duration: ${VALID_DURATION} # in second
  refreshable-duration: ${REFRESHABLE_DURATION} # in second

app:
  init-admin-account:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  role:
    admin:
      name: ADMIN
      description: "Admin has all authorization"
  controller:
    user:
      response:
        delete:
          success: "User has been deleted"
    role:
      response:
        delete:
          success: "Role has been deleted"
    permission:
      response:
        delete:
          success: "Permission has been deleted"
    authentication:
      response:
        logout:
          success: "Logout successfully"
        change-password:
          success: "Password has been changed"
  email:
    verification:
      expiration: 5 # in minute
      reset-password:
        length: 6
    host: ${EMAIL_BASE_URL}
    API-key: ${EMAIL_API_KEY}
    endpoint: ${EMAIL_ENDPOINT}
    subject: "React To Spring Forums"
    sender:
      email: ${SENDER_EMAIL}
      name : ${SENDER_NAME}





open:
  api:
    title: "React To Spring Forums API"
    version: "v1.0.0"
    description: "API for React To Spring Forums"
    server:
      url: "http://localhost:8080/api"
      description: "Local Server."
    group:
      package-to-scan: "com.react_to_spring.React_To_Spring_Forums.controller"